#!/bin/bash
#
#loop to read numbers to be rounded down from list (text file)
#
#at line 11, change list.txt to the filename of your own list
#
#after configuring the rounding-down-module, run this file via bash read_list, and the rest is automated
#


input="list.txt"
while IFS= read -r line
do
  echo "$line" > full_number_1.txt && bash rounding-up-module-v102-for-lists.sh
done < "$input"


#V
