#!/bin/bash
#
#loop to read numbers to be rounded up from list (text file)
#
#at line 11, change list.txt to the filename of your own list
#
#after configuring the rounding-up-module, run this file via bash read_list, and the rest is automated.
#the result will be a new text file where each line number holds a rounded number instead of the original number
#(i.e. you can compare the original list with the new list line by line)

input="list.txt"
while IFS= read -r line
do
  echo "$line" > full_number_1.txt && bash rounding-up-module-v101-for-lists.sh
done < "$input"


#V
